#!/usr/bin/env python3
"""Report Generator — Produce .md audit reports"""

import os
from datetime import datetime
from pathlib import Path


class AuditReport:
    def __init__(self, target: str, report_type: str):
        self.target = target
        self.report_type = report_type
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.filename = f"reports/{report_type}-{self._slugify(target)}-{datetime.now().strftime('%Y-%m-%d')}.md"
        self.findings = []
        self.start_time = __import__('time').time()

    def _slugify(self, text: str) -> str:
        text = text.replace("https://", "").replace("http://", "").replace("/", "-").replace(".", "-")
        text = text.replace(" ", "-").replace("  ", "-")
        return text[:50]

    def add_finding(self, severity: str, title: str, detail: str = "", fix: str = ""):
        self.findings.append({"severity": severity, "title": title, "detail": detail, "fix": fix})

    def generate(self) -> str:
        elapsed = __import__('time').time() - self.start_time
        report = self._build_header(elapsed) + "\n\n"
        report += self._build_summary() + "\n\n"
        report += self._build_findings() + "\n\n"
        report += self._build_footer()
        os.makedirs("reports", exist_ok=True)
        with open(self.filename, "w") as f:
            f.write(report)
        return self.filename

    def _build_header(self, elapsed: float) -> str:
        return f"# 🔐 FullTestSec Audit Report\n\n**Target:** `{self.target}`  \n**Type:** {self.report_type}  \n**Date:** {self.timestamp}  \n**Duration:** {elapsed:.1f}s  \n\n---\n\n"

    def _build_summary(self) -> str:
        counts = {"🔴 Critical": 0, "🟠 High": 0, "🟡 Medium": 0, "🔵 Low": 0, "✅ Pass": 0}
        sev_map = {"critical": "🔴 Critical", "high": "🟠 High", "medium": "🟡 Medium", "low": "🔵 Low", "ok": "✅ Pass"}
        for f in self.findings:
            cat = sev_map.get(f["severity"], "🔵 Low")
            counts[cat] = counts.get(cat, 0) + 1
        total = sum(counts.values())
        score = max(0, 100 - (counts.get("🔴 Critical", 0) * 20 + counts.get("🟠 High", 0) * 10 + counts.get("🟡 Medium", 0) * 5))

        lines = ["## 📊 Summary", "", f"**Security Score:** {score}/100 {'✅' if score >= 80 else '⚠️' if score >= 50 else '🔴'}", "", "| Severity | Count |", "|----------|-------|"]
        for sev, count in counts.items():
            lines.append(f"| {sev} | {count} |")
        lines.append(f"| **Total** | **{total}** |")
        return "\n".join(lines)

    def _build_findings(self) -> str:
        lines = ["## 🔍 Findings", ""]
        ordered = {"critical": [], "high": [], "medium": [], "low": [], "ok": []}
        for f in self.findings:
            ordered.setdefault(f["severity"], []).append(f)
        for sev, emoji in [("critical", "🔴 CRITICAL"), ("high", "🟠 HIGH"), ("medium", "🟡 MEDIUM"), ("low", "🔵 LOW"), ("ok", "✅ PASS")]:
            items = ordered.get(sev, [])
            if not items:
                continue
            lines.append(f"### {emoji}")
            lines.append("")
            for i, f in enumerate(items, 1):
                lines.append(f"**{i}. {f['title']}**  ")
                if f["detail"]:
                    lines.append(f"   - *Detail:* {f['detail']}  ")
                if f["fix"]:
                    lines.append(f"   - *Fix:* `{f['fix']}`  ")
                lines.append("")
        return "\n".join(lines)

    def _build_footer(self) -> str:
        return f"---\n\n*Report generated by **FullTestSec** — {self.timestamp}*\n*Full Testing & Security Testing Suite* 🔐"
